# Generated by Django 5.0.6 on 2024-07-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('Bank Slip', 'BANK SLIP'), ('credit', 'CREDIT CARD'), ('debit', 'DEBIT CARD'), ('Pix', 'PIX'), ('Ted', 'TED'), ('Cash', 'CASH'), ('Check', 'CHECK'), ('Deposit', 'DEPOSIT'), ('Debit Bank', 'DEBIT BANK')], max_length=120),
        ),
    ]
