# Generated by Django 5.0.6 on 2024-07-07 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=18)),
                ('city', models.CharField(max_length=150)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='states.state')),
            ],
        ),
    ]
