# Generated by Django 5.0.6 on 2024-07-08 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('account', models.CharField(max_length=20)),
                ('agency', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=150)),
                ('manager', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado', to='states.state')),
            ],
        ),
    ]
