# Generated by Django 5.0.6 on 2024-07-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=12)),
                ('order_date', models.DateField()),
                ('order_supplier', models.CharField(max_length=150)),
                ('order_amout', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
