# Generated by Django 5.0.6 on 2024-07-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_amout',
            new_name='order_amount',
        ),
    ]
